name: analytics

on:
  push:
    branches:
      - main

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: run
        run: pip install -r requirements.txt && python single_analysis.py && python create_readme.py
      - name: GIT commit and push all changed files
        env: 
          CI_COMMIT_MESSAGE: Automatic analytics
          CI_COMMIT_AUTHOR: Continuous Integration
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add out/\*
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
